### ISSUE TITLE
gui for SRGAN

### ISSUE THREAD

**Issue by ABDOELSHEMY** [tensorlayer/srgan#1]

**Comment by zsdonghao** [comment]
hi, in this repo, before you can use SRGAN, you need to train the network via `main.py`, so you should have a GPU machine~ a basic guide as below:

- 1. download image dataset manual as the readme show.
- 2. download VGG19 model manual as the readme show.
- 3. run these in your terminal:
```
pip install tensorflow-gpu
pip install tensorlayer
python main.py
python main.py --mode=evaluate 
```

**Comment by ABDOELSHEMY** [comment]
ok ، thanks for quick replay ، seem to be sample enough now to me to use it .

**Comment by Andreababy** [comment]
i cannot download the "DIV2K - bicubic downscaling x4 competition " dataset, can you give me a link? thank you very much. @zsdonghao

**Comment by zsdonghao** [comment]
@Andreababy as you say you are training the network in another issue, i think you already got the images right?

**Comment by Andreababy** [comment]
i have already downloaded the dataset .but ,when i trained my own picture，the resolution quanlity is poor. is there some request  resolution in my test picture？
