### ISSUE TITLE
Restart training from breakpoint

### ISSUE THREAD

**Issue by Essenlin** [tensorlayer/srgan#10]
How can I start training from breakpoint ? @zsdonghao

**Comment by zsdonghao** [comment]
Hi, to restore a model, you will need to save the model via `tl.files.save_npz()` and then restore the model via `tl.files.load_and_assign_npz`.

TF provides several ways to save and restore model, you may want this link: http://tensorlayer.readthedocs.io/en/latest/modules/files.html#load-and-save-network

**Comment by JustinhoCHN** [comment]
hi @Essenlin , this source code will automatically restore the checkpoint once you restart the model training , so don't worry about how to rewrite the code to training from breakpoint.

**Comment by Essenlin** [comment]
Thanks @zsdonghao @JustinhoCHN

**Comment by amrbenattia** [comment]
@JustinhoCHN , thanks for your answer but I wonder when I train my model, g_srgan.npz file is save at checkpoint file. 
How epoch this file is upadated ? and if the training dropped at epoch 1000 out of 2000 how to continue training from that epoch ?
Thanks in advance

**Comment by JustinhoCHN** [comment]
@amrbenattia as far as I can remember, srgan will save checkpoint file every 50 epochs. And the training code will restore the checkpoint automatically, it means it will restart at wherever you left before.

**Comment by not-a-swiss-conductor** [comment]
@JustinhoCHN   Excuse me, I have a problem about checkpoints. I have run SRGAN about 350 epoch, and there are three files in checkpoint exactly. However, when I start 'main' again, after initial test 100 epoch, it still begins at 0/2000 ans runs over and over again. It seems that the checkpoint doesn't work.
Nevertheless, it shows load xxx.npz SUCCESS! I couldn't figure out why, could you please help me?

**Comment by JustinhoCHN** [comment]
@not-a-swiss-conductor don't mind this 0/2000, it already restore the weights, 0/2000 just means you have 2000 epochs to train, not train from scratch.

**Comment by hiankun** [comment]
@JustinhoCHN Sorry to ask question in the closed thread, but I was checking the code and cannot figure out how does it restore the latest checkpoints.

In the `train.py` script, the `train()` function create G and D models by using `get_G` and `get_D`, respectively. In both `get_G` and `get_D`, the weights are initialized by `tf.random_normal_initializer`. Based on the code, it looks like that the models will be reset to random weights, doesn't it?

Should I check other part of the source code in which I can find the reloading mechanism when we try to re-train the models with latest checkpoints (g.h5 and d.h5 by default)?

**Comment by JustinhoCHN** [comment]
@hiankun I think the code was updated in 2019, early in 2017, the ```main.py``` (now is ```train.py```) contains the part of retoring the model from checkpoints. Maybe you should write the restoring part by yourself.
