### ISSUE TITLE
please provide d_srgan.npz

### ISSUE THREAD

**Issue by akshay951228** [tensorlayer/srgan#105]
if provide discriminate trained weight would be helpful. I would like to use it for transfer learning.

**Comment by zsdonghao** [comment]
it is provided. check readme.

**Comment by akshay951228** [comment]
you provide g_srgan.npz but I need **d_srgan.npz** to resume training from there

**Comment by zsdonghao** [comment]
oh, i see, that model is too big .. and actually, in my view, it is not useful for transfer learning.

However, if you want to have one, you can train the D with pre-trained G with 1 epoch.
