### ISSUE TITLE
Online discussion open

### ISSUE THREAD

**Issue by zsdonghao** [tensorlayer/srgan#11]
Please join Slack,  the invite link as follow:

https://join.slack.com/t/tensorlayer/shared_invite/MjExMjMzODAwNjI0LTE0OTk4ODEzMjUtNmVjNjQ4ZjMzMw

**Comment by dbachko** [comment]
@zsdonghao can you update this invite link please? It is dead: **_This invite link is no longer active._**

**Comment by zsdonghao** [comment]
update link: https://join.slack.com/t/tensorlayer/shared_invite/enQtMjUyMjczMzU2Njg4LWI0MWU0MDFkOWY2YjQ4YjVhMzI5M2VlZmE4YTNhNGY1NjZhMzUwMmQ2MTc0YWRjMjQzMjdjMTg2MWQ2ZWJhYzc

**Comment by ontheway16** [comment]
Is Slack channel still active? it says **"Something's amiss with your invitation........"**

**Comment by zsdonghao** [comment]
the latest invitation link is in [gitter](https://gitter.im/tensorlayer/Lobby#?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
