### ISSUE TITLE
OOM error with CPU

### ISSUE THREAD

**Issue by JadenLy** [tensorlayer/srgan#126]
Thanks for your incredible work on the implementation. I want to train a SRGAN with my own dataset, which includes 1280 training images and 69 validation images. Images have at most around 3000x4000 dimension and at least around 1000x1400. I set the batch size to 4, number of threads to 8 and still received the following error. I wonder what else can I change. 

Configruation: Ubuntu 16.04, CUDA 10.0, TF1.11, GPU V100, 8 vCPUs and 40 GB RAM. 

> [TL]
> WARNING: this method is DEPRECATED and has no effect, please remove it from your code.
> build model started
> build model finished: 0.405995s
> build model started
> build model finished: 0.133922s
> 2018-11-18 22:57:11.368925: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
> 2018-11-18 22:57:11.369904: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: ml-yang-20181102
> 2018-11-18 22:57:11.369916: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: ml-yang-20181102
> 2018-11-18 22:57:11.372246: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 410.48.0
> 2018-11-18 22:57:11.372300: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 410.48.0
> 2018-11-18 22:57:11.372320: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 410.48.0
> [TL] WARNING: Function: `tensorlayer.layers.utils.initialize_global_variables` (in file: /home/i_leyang/.local/lib/python2.7/site-packages/tensorlayer/layers/utils.py) is deprecated and will be removed after 2018-09-30.
> Instructions for updating: This API is deprecated in favor of `tf.global_variables_initializer`
> 
> 2018-11-18 22:57:11.857700: W tensorflow/core/framework/allocator.cc:113] Allocation of 134217728 exceeds 10% of system memory.
> 2018-11-18 22:57:11.859221: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at constant_op.cc:169 : Resource exhausted: OOM when allocating tensor with shape[4,4,1024,2048] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
> 2018-11-18 22:57:11.859291: W tensorflow/core/framework/allocator.cc:113] Allocation of 134217728 exceeds 10% of system memory.
> 2018-11-18 22:57:11.859336: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at constant_op.cc:169 : Resource exhausted: OOM when allocating tensor with shape[4,4,1024,2048] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
> 2018-11-18 22:57:12.006870: W tensorflow/core/framework/allocator.cc:113] Allocation of 134217728 exceeds 10% of system memory.
> 2018-11-18 22:57:12.007710: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at constant_op.cc:169 : Resource exhausted: OOM when allocating tensor with shape[4,4,1024,2048] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
> 2018-11-18 22:57:12.007799: W tensorflow/core/framework/allocator.cc:113] Allocation of 134217728 exceeds 10% of system memory.
> 2018-11-18 22:57:12.007833: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at constant_op.cc:169 : Resource exhausted: OOM when allocating tensor with shape[4,4,1024,2048] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> Aborted

Please help, thanks!

**Comment by mexicantexan** [comment]
Those images appear to be way to large for your system to handle. I would suggest preprocessing them to a smaller size.

**Comment by Pamulapati13** [comment]
try google colab
