### ISSUE TITLE
"'time' is not defined" error while training

### ISSUE THREAD

**Issue by bberry17** [tensorlayer/srgan#148]
NameError: name 'time' is not defined
same as #76, #91 but I can't find a solution...
 Where should I add exactly ' import time' in model.py?
I tried like 10 times to add import time in model.py, but it didn't work..

**Comment by Fredy** [comment]
Can you paste the complete error log, please?

**Comment by bberry17** [comment]
> Can you paste the complete error log, please?

![image](https://user-images.githubusercontent.com/45968511/60117479-193fd800-97b5-11e9-98f3-ccbf7abae050.png)

When I put 'import time' on the lin #4 in model.py, I got a new error code like image.

  File "train.py", line 101, in train
    fake_hr_patchs = G(lr_patchs)
AttributeError: 'Model' object has no attribute 'weights'

What should I do for this error ?.....

**Comment by Fredy** [comment]
Change all the `weights` occurrences with `trainable_weights`
There are other problems in `train.py`.
 I'm using the same `train.py` but for different generator and discriminator I have fixed the errors, but also I have change other things, you can check it [here](https://github.com/Fredy/srgan-1/blob/master/train.py)

**Comment by bberry17** [comment]
> Change all the `weights` occurrences with `trainable_weights`
> There are other problems in `train.py`.
> I'm using the same `train.py` but for different generator and discriminator I have fixed the errors, but also I have change other things, you can check it [here](https://github.com/Fredy/srgan-1/blob/master/train.py)

Thank you, I just downloaded your file and trained it. 
There is no more error but, after training I tried python main.py --mode=evaluate and error again. 
like below image,  
![image](https://user-images.githubusercontent.com/45968511/60120676-5eb3d380-97bc-11e9-9e61-cf611a0545ef.png)

Do you solve this error, too?

**Comment by Fredy** [comment]
I haven't fixed those things yet, sorry.
BTW I changed `generator_train`, `_map_fn_train` and excluded the VGG error part

**Comment by bberry17** [comment]
> I haven't fixed those things yet, sorry.
> BTW I changed `generator_train`, `_map_fn_train` and excluded the VGG error part

Thank you so much, I will be very appreciated if you reply again for this post after fix that error. 
I will try, too.
Thank you.

**Comment by Kjos** [comment]
Change the first two G.weights to G.trainableweights and add time, random again as final import:

import time, random
from datetime import datetime
import numpy as np
import scipy, multiprocessing
import tensorflow as tf
import tensorlayer as tl
from model import get_G, get_D
from config import config
import time, random

**Comment by munitech4u** [comment]
> Change the first two G.weights to G.trainableweights and add time, random again as final import:
> 
> import time, random
> from datetime import datetime
> import numpy as np
> import scipy, multiprocessing
> import tensorflow as tf
> import tensorlayer as tl
> from model import get_G, get_D
> from config import config
> import time, random

it should be G.trainable_weights and not "G.trainableweights"
