### ISSUE TITLE
Incompatable shapes: [2] vs. [3]

### ISSUE THREAD

**Issue by CharlesDove** [tensorlayer/srgan#157]
While running train.py, the program fails at the line:
`  for step, (lr_patchs, hr_patchs) in enumerate(train_ds):`
And throws the error:
`2019-07-17 00:07:26.604020: W tensorflow/core/framework/op_kernel.cc:1546] OP_REQUIRES failed at iterator_ops.cc:1055 : Invalid argument: Incompatible shapes: [2] vs. [3]
         [[{{node random_crop/GreaterEqual}}]]`

I'm using my own dataset of 512x512 images.  Many thanks for any help!
Using Tensorflow 2.0.0 and Tensorlayer 2.1.0.

The entire program output:
`2019-07-17 00:07:11.210033: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library nvcuda.dll
2019-07-17 00:07:11.324255: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties:
name: GeForce GTX 660 Ti major: 3 minor: 0 memoryClockRate(GHz): 1.0975
pciBusID: 0000:01:00.0
2019-07-17 00:07:11.326948: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-07-17 00:07:11.330343: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1717] Ignoring visible gpu device (device: 0, name: GeForce GTX 660 Ti, pci
bus id: 0000:01:00.0, compute capability: 3.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.
2019-07-17 00:07:11.335968: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-17 00:07:11.337660: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]
WARNING: Logging before flag parsing goes to stderr.
W0717 00:07:11.363939  4156 deprecation.py:323] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\data\ops\dataset_ops.py:505: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means tf.py_functions can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.

generator(
  (_inputlayer_1): Input(shape=(10, None, None, 3), name='_inputlayer_1')
  (conv2d_1): Conv2d(in_channels=3, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv2d_1')
  (conv2d_2): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_2')
  (batchnorm_1): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_1")
  (conv2d_3): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_3')
  (batchnorm_2): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_2")
  (elementwise_1): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_1')
  (conv2d_4): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_4')
  (batchnorm_3): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_3")
  (conv2d_5): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_5')
  (batchnorm_4): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_4")
  (elementwise_2): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_2')
  (conv2d_6): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_6')
  (batchnorm_5): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_5")
  (conv2d_7): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_7')
  (batchnorm_6): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_6")
  (elementwise_3): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_3')
  (conv2d_8): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_8')
  (batchnorm_7): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_7")
  (conv2d_9): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_9')
  (batchnorm_8): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_8")
  (elementwise_4): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_4')
  (conv2d_10): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_10')
  (batchnorm_9): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_9")
  (conv2d_11): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_11')
  (batchnorm_10): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_10")
  (elementwise_5): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_5')
  (conv2d_12): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_12')
  (batchnorm_11): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_11")
  (conv2d_13): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_13')
  (batchnorm_12): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_12")
  (elementwise_6): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_6')
  (conv2d_14): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_14')
  (batchnorm_13): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_13")
  (conv2d_15): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_15')
  (batchnorm_14): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_14")
  (elementwise_7): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_7')
  (conv2d_16): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_16')
  (batchnorm_15): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_15")
  (conv2d_17): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_17')
  (batchnorm_16): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_16")
  (elementwise_8): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_8')
  (conv2d_18): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_18')
  (batchnorm_17): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_17")
  (conv2d_19): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_19')
  (batchnorm_18): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_18")
  (elementwise_9): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_9')
  (conv2d_20): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_20')
  (batchnorm_19): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_19")
  (conv2d_21): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_21')
  (batchnorm_20): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_20")
  (elementwise_10): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_10')
  (conv2d_22): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_22')
  (batchnorm_21): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_21")
  (conv2d_23): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_23')
  (batchnorm_22): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_22")
  (elementwise_11): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_11')
  (conv2d_24): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_24')
  (batchnorm_23): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_23")
  (conv2d_25): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_25')
  (batchnorm_24): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_24")
  (elementwise_12): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_12')
  (conv2d_26): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_26')
  (batchnorm_25): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_25")
  (conv2d_27): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_27')
  (batchnorm_26): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_26")
  (elementwise_13): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_13')
  (conv2d_28): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_28')
  (batchnorm_27): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_27")
  (conv2d_29): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_29')
  (batchnorm_28): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_28")
  (elementwise_14): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_14')
  (conv2d_30): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_30')
  (batchnorm_29): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_29")
  (conv2d_31): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_31')
  (batchnorm_30): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_30")
  (elementwise_15): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_15')
  (conv2d_32): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_32')
  (batchnorm_31): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, relu, name="batchnorm_31")
  (conv2d_33): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_33')
  (batchnorm_32): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_32")
  (elementwise_16): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_16')
  (conv2d_34): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_34')
  (batchnorm_33): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_33")
  (elementwise_17): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, No Activation, name='elementwise_17')
  (conv2d_35): Conv2d(in_channels=64, out_channels=256, kernel_size=(3, 3), strides=(1, 1), padding=SAME, No Activation, name='conv2d_35')
  (subpixelconv2d_1): SubpixelConv2d(in_channels=256, out_channels=64, relu, name='subpixelconv2d_1')
  (conv2d_36): Conv2d(in_channels=64, out_channels=256, kernel_size=(3, 3), strides=(1, 1), padding=SAME, No Activation, name='conv2d_36')
  (subpixelconv2d_2): SubpixelConv2d(in_channels=256, out_channels=64, relu, name='subpixelconv2d_2')
  (conv2d_37): Conv2d(in_channels=64, out_channels=3, kernel_size=(1, 1), strides=(1, 1), padding=SAME, tanh, name='conv2d_37')
)
discriminator(
  (_inputlayer_2): Input(shape=(10, None, None, 3), name='_inputlayer_2')
  (conv2d_38): Conv2d(in_channels=3, out_channels=64, kernel_size=(4, 4), strides=(2, 2), padding=SAME, <lambda>, name='conv2d_38')
  (conv2d_39): Conv2d(in_channels=64, out_channels=128, kernel_size=(4, 4), strides=(2, 2), padding=SAME, bias=False, No Activation, name='conv2d_39')
  (batchnorm_34): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, <lambda>, name="batchnorm_34")
  (conv2d_40): Conv2d(in_channels=128, out_channels=256, kernel_size=(4, 4), strides=(2, 2), padding=SAME, bias=False, No Activation, name='conv2d_40')
  (batchnorm_35): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, <lambda>, name="batchnorm_35")
  (conv2d_41): Conv2d(in_channels=256, out_channels=512, kernel_size=(4, 4), strides=(2, 2), padding=SAME, bias=False, No Activation, name='conv2d_41')
  (batchnorm_36): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, <lambda>, name="batchnorm_36")
  (conv2d_42): Conv2d(in_channels=512, out_channels=1024, kernel_size=(4, 4), strides=(2, 2), padding=SAME, bias=False, No Activation, name='conv2d_42')
  (batchnorm_37): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, <lambda>, name="batchnorm_37")
  (conv2d_43): Conv2d(in_channels=1024, out_channels=2048, kernel_size=(4, 4), strides=(2, 2), padding=SAME, bias=False, No Activation, name='conv2d_43')
  (batchnorm_38): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, <lambda>, name="batchnorm_38")
  (conv2d_44): Conv2d(in_channels=2048, out_channels=1024, kernel_size=(1, 1), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_44')
  (batchnorm_39): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, <lambda>, name="batchnorm_39")
  (conv2d_45): Conv2d(in_channels=1024, out_channels=512, kernel_size=(1, 1), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_45')
  (batchnorm_40): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_40")
  (conv2d_46): Conv2d(in_channels=512, out_channels=128, kernel_size=(1, 1), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_46')
  (batchnorm_41): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, <lambda>, name="batchnorm_41")
  (conv2d_47): Conv2d(in_channels=128, out_channels=128, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_47')
  (batchnorm_42): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, <lambda>, name="batchnorm_42")
  (conv2d_48): Conv2d(in_channels=128, out_channels=512, kernel_size=(3, 3), strides=(1, 1), padding=SAME, bias=False, No Activation, name='conv2d_48')
  (batchnorm_43): BatchNorm(num_features=None, decay=0.9, epsilon=1e-05, No Activation, name="batchnorm_43")
  (elementwise_18): Elementwise(combine_fn=<function add at 0x000002094EDC9A60>, <lambda>, name='elementwise_18')
  (flatten_1): Flatten(name='flatten_1')
  (dense_1): Dense(n_units=1, No Activation, in_channels='512', name='dense_1')
)
model(
  (_inputlayer_3): Input(shape=[None, 224, 224, 3], name='_inputlayer_3')
  (scale): Lambda(fn=<function VGG_static.<locals>.<lambda> at 0x0000020929713378>,len_weights=0,name='scale')
  (layerlist_1): LayerList(
    (0): Conv2d(in_channels=3, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv1_1')
    (1): Conv2d(in_channels=64, out_channels=64, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv1_2')
    (2): MaxPool2d(filter_size=(2, 2), strides=(2, 2), padding=SAME, name='pool1')
    (3): Conv2d(in_channels=64, out_channels=128, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv2_1')
    (4): Conv2d(in_channels=128, out_channels=128, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv2_2')
    (5): MaxPool2d(filter_size=(2, 2), strides=(2, 2), padding=SAME, name='pool2')
    (6): Conv2d(in_channels=128, out_channels=256, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv3_1')
    (7): Conv2d(in_channels=256, out_channels=256, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv3_2')
    (8): Conv2d(in_channels=256, out_channels=256, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv3_3')
    (9): Conv2d(in_channels=256, out_channels=256, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv3_4')
    (10): MaxPool2d(filter_size=(2, 2), strides=(2, 2), padding=SAME, name='pool3')
    (11): Conv2d(in_channels=256, out_channels=512, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv4_1')
    (12): Conv2d(in_channels=512, out_channels=512, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv4_2')
    (13): Conv2d(in_channels=512, out_channels=512, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv4_3')
    (14): Conv2d(in_channels=512, out_channels=512, kernel_size=(3, 3), strides=(1, 1), padding=SAME, relu, name='conv4_4')
    (15): MaxPool2d(filter_size=(2, 2), strides=(2, 2), padding=SAME, name='pool4')
  )
)
2019-07-17 00:07:26.604020: W tensorflow/core/framework/op_kernel.cc:1546] OP_REQUIRES failed at iterator_ops.cc:1055 : Invalid argument: Incompatible shapes: [2] vs. [3]
         [[{{node random_crop/GreaterEqual}}]]`

**Comment by lunayang712** [comment]
Hi! Have you figured it out? I also have this issue.

**Comment by zsdonghao** [comment]
Fix in here https://github.com/tensorlayer/srgan/releases/tag/1.4.0
