### ISSUE TITLE
Import error - ModuleNotFoundError: No module named 'model'

### ISSUE THREAD

**Issue by munitech4u** [tensorlayer/srgan#159]
While trying to make sure the all packages are there. This import statement in train.py is throwing error:

from model import get_G, get_D

ModuleNotFoundError: No module named 'model'

I can't find any such package 'model' from PyPi.org. What is it that I am missing here?

**Comment by zsdonghao** [comment]
the model file is here https://github.com/tensorlayer/srgan/blob/master/model.py   ......
