### ISSUE TITLE
请问如果图片太多，一直加载不出来怎么办？

### ISSUE THREAD

**Issue by YonghuiXu** [tensorlayer/srgan#163]
## If your machine have enough memory, please pre-load the whole train set.
    train_hr_imgs = tl.vis.read_images(train_hr_img_list, path=config.TRAIN.hr_img_path, n_threads=32)

**Comment by ChrisWu1997** [comment]
As the comment suggested, if you do not have enough memory to pre-load the whole dataset, only load a image when it is needed. You may need to change the `get_train_data` function in `train.py`

**Comment by zsdonghao** [comment]
@ChrisWu1997 yes, I also set the batch size of the the latest commit to be 8, machine will low GPU memory should be available.

**Comment by YonghuiXu** [comment]
Thanks, now I reduce images from 200000 to 50000.
