### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Matrix size-incompatible: In[0]: [4,18432], In[1]: [512,1] [Op:MatMul] name: MatMul/

### ISSUE THREAD

**Issue by AndrzejBandurski** [tensorlayer/srgan#166]
unfortunately this code is not working at all, 
please repair the issues, test it and share again,
or give at least a notice "NOT WORKING AT ALL"

you last update from 2 days ago gives an error... ( like all the code before )
"... tensorflow.python.framework.errors_impl.InvalidArgumentError: Matrix size-incompatible: In[0]: [4,18432], In[1]: [512,1] [Op:MatMul] name: MatMul/ "

moving on to somewhere less time wasting !
cheers

**Comment by zsdonghao** [comment]
Fix in here https://github.com/tensorlayer/srgan/releases/tag/1.4.0
