### ISSUE TITLE
How to test on custom image?

### ISSUE THREAD

**Issue by kapilsarwat** [tensorlayer/srgan#171]
Python train.py --mode=evaluate is running only for some images in valid_hr and valid_lr directories.
Is there any way to run the model for test_lr?
@zsdonghao

**Comment by ChrisWu1997** [comment]
I think it's easy to modify a few line of the `evaluate` function in `train.py` to enable testing on customized image.
https://github.com/tensorlayer/srgan/blob/aeca83bc85adabdefa0e75db470379b878e54051/train.py#L167

**Comment by kapilsarwat** [comment]
Ok thanks
