### ISSUE TITLE
The BatchNorm is not defined

### ISSUE THREAD

**Issue by leffey** [tensorlayer/srgan#181]
Traceback (most recent call last):
  File "train.py", line 202, in <module>
    train()
  File "train.py", line 74, in train
    G = get_G((batch_size, 96, 96, 3))
  File "/xx/SR/srgan-tf/model.py", line 27, in get_G
    n = BatchNorm(gamma_init=g_init)(n)
NameError: name 'BatchNorm' is not defined

why ?

**Comment by mcDandy** [comment]
The same happened to me, but on windows.

**Comment by zsdonghao** [comment]
are you sure you are using the latest code?

**Comment by mcDandy** [comment]
Yes. Cloned from master 4 days ago.

Dne pá 11. říj 2019 13:37 uživatel Hao <notifications@github.com> napsal:

**Comment by mcDandy** [comment]
fixed it in my pull reqest

**Comment by rinabell** [comment]
it happened to me, but another machine works well with the same environment...
could not find why

**Comment by sherinaly** [comment]
I am running the srgan code on coLab and same error happens. It is running under Tf 2 and TL 2. Any one knows how to solve this?

**Comment by mcDandy** [comment]
I had same error. It was on windows. You will need to import BatchNorm from
the same library (or how it is called in python) as BatchNorm2d

Dne ne 27. říj 2019 16:21 uživatel sherinaly <notifications@github.com>
napsal:

**Comment by sherinaly** [comment]
Solved, I included BatchNorm in the model file.
Thank you
