### ISSUE TITLE
generated image with serious checkboard(or mosaic)

### ISSUE THREAD

**Issue by yugsdu** [tensorlayer/srgan#187]
Hello, author. I run your code without modification, but the resulted image has serious checkboard / mosaic shape. Could you tell me why? Have you met this problem before? How should I do to solve it? Thank you very much. 

"this is original image"
![0801](https://user-images.githubusercontent.com/35397579/67174446-9cd0a500-f3f4-11e9-8a21-cfcfe7dc3206.png)

"this is resulted image"
![girl_gen](https://user-images.githubusercontent.com/35397579/67174447-9d693b80-f3f4-11e9-96fe-290e56a117d5.png)

**Comment by zsdonghao** [comment]
did you finish the training?

**Comment by yugsdu** [comment]
> did you finish the training?

Thank you for replying me imediately. Indeed, I really finished the training. I even set the epoch larger for second training. However, the resulted image still unpleasant. I get lost...

**Comment by zsdonghao** [comment]
I see, could you show the output images for different epoch? so that I can check what is the problem..

I doubt it is caused by the TensorFlow version..

**Comment by yugsdu** [comment]
> I see, could you show the output images for different epoch? so that I can check what is the problem..
> 
> I doubt it is caused by the TensorFlow version..

Thank you. Since I didn't modify this code, in ./samples/srgan_gan, these are some results as below. As for resulted image for this "girl" image in different epochs, maybe I should retrian the model again.
![train_10](https://user-images.githubusercontent.com/35397579/67175579-38641480-f3f9-11e9-9c2a-a5e2b37af95b.png)
![train_20](https://user-images.githubusercontent.com/35397579/67175580-38fcab00-f3f9-11e9-8141-2b3623ef1bec.png)
![train_1420](https://user-images.githubusercontent.com/35397579/67175581-39954180-f3f9-11e9-9a8c-bba9740e202d.png)
![train_1500](https://user-images.githubusercontent.com/35397579/67175582-39954180-f3f9-11e9-93ef-1e072c42829f.png)
As for Tensorflow version, I used 1.8.0.

**Comment by yugsdu** [comment]
I see. I made a mistake... When I train the model from the scratch with your dataset, it is OK. However, when I tried to test the "gril" image, it didn't work because of its bmp format...
That maybe the image forma(jpg, bmp, png) problem.
Thank you anyway.

**Comment by zsdonghao** [comment]
Cool, great to hear that.
