### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'Conv2dLayer' and 'float'

### ISSUE THREAD

**Issue by yugsdu** [tensorlayer/srgan#188]
Hello author, when I tried to modify your resdiual block code with a scaling factor 0.1, I met this probelm: "TypeError: unsupported operand type(s) for *: 'Conv2dLayer' and 'float'". 
I have tried to find solutions in "tensorlayer" but failed.
Could you tell me how should I do to multiply scaling factor?

Sorry for disturbing you again...

"this is your original code"
![image](https://user-images.githubusercontent.com/35397579/67254695-0b733880-f4b1-11e9-8acf-3d2053697f49.png)

"this is I modified code with scaling factor"
![image](https://user-images.githubusercontent.com/35397579/67254804-aa983000-f4b1-11e9-90ea-088466c3c190.png)

**Comment by zsdonghao** [comment]
no `Conv2dLayer` in your code ..

please use Scale layer, instead of 0.1*nn

**Comment by yugsdu** [comment]
Emm, I seemd to make a stupid mistake again...
Thank you very much!
