### ISSUE TITLE
Error loading vgg19 after downloading vgg19.npy

### ISSUE THREAD

**Issue by mustaeenqazi** [tensorlayer/srgan#222]
Hi, i have downloaded the vgg19.npy file as decribed. and put it in the   /tensorlayer/models. and then ran the code for training but i still get the error, error log is attached as an image, 
it seems that the code is unable read the vgg19.npy file.
![error_loading_vgg19](https://user-images.githubusercontent.com/66418760/95310341-96993a00-088c-11eb-9c7a-395a875c75c9.JPG)

**Comment by zsdonghao** [comment]
don't need to put it into tensorlayer/models

**Comment by mustaeenqazi** [comment]
Thank you very much, Can you please explain how the download works using the tuturial_models_vgg19.py,
Because the line VGG = tl.models.vgg19(pretrained=True, end_with='pool4', mode='static') in the file  train.py should load the vgg19 itself, without any external downloading

**Comment by zsdonghao** [comment]
@Laicheng0830 founds the github link was updated, the latest commit will help you handle it.

**Comment by mustaeenqazi** [comment]
Thanks, I checked Issue number 216, The solution at the end helped me , instead of giving a .npy file with the git link i used the vgg19.npy from the dropbox link provided there with all the weights itself and commented the line 158 in tensorlayer/models/vgg.py  "#maybe_download_and_extract(model_saved_name[layer_type], 'models', model_urls[layer_type])"
