### ISSUE TITLE
cannot import name 'Linear' from 'tensorlayerx.nn'

### ISSUE THREAD

**Issue by Zhyixin** [tensorlayer/srgan#243]
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    from srgan import SRGAN_g, SRGAN_d
  File "..\srgan.py", line 4, in <module>
    from tensorlayerx.nn import Linear, MaxPool2d
ImportError: cannot import name 'Linear' from 'tensorlayerx.nn'

How can I solve this problem?

**Comment by AIisCool** [comment]
I'm having the same issue too.

**Comment by hanjr92** [comment]
hello，please install via source
`pip install git+https://github.com/tensorlayer/tensorlayerx.git `
