### ISSUE TITLE
How to input images with different sizes in the test stage?

### ISSUE THREAD

**Issue by yufanLIU** [tensorlayer/srgan#40]

**Comment by zsdonghao** [comment]
i have the same problem as well. @yufanLIU can it be solved if you update to the latest TL version?

**Comment by zhuguoguo123** [comment]
这个是变量共享的问题，我笨笨的这样做了一下 可以正常运行了
if(epoch==0):
    netname= SRGAN_g2(t_image, is_train=False, reuse=False)
else:
    netname= SRGAN_g2(t_image, is_train=False, reuse=True)

这个链接可能会有用
http://zhangzhenyuan163.blog.163.com/blog/static/858193892017313102658544

**Comment by yufanLIU** [comment]
@zsdonghao The "SubpixelConv2d"  layer in the latest TL version can solve this problem, but you need to do these things:
1. add codes in this layer:
`a = tf.shape(X)[1]
b = tf.shape(X)[2]`
(Handling Dimension(None) type for undefined height and width dim)
2. re-train this model. Because the PS transformation is different from that in old version.

**Comment by zsdonghao** [comment]
@yufanLIU cool, thank you very much~

**Comment by yufanLIU** [comment]
@zhuguoguo123 我这么改好像不行诶。  你测试的时候也是这么做的吗？
