### ISSUE TITLE
Is there any pretrained model?

### ISSUE THREAD

**Issue by tuxzz** [tensorlayer/srgan#51]
I found this model is hard to train with my dataset on my machine.
Is there any pretrained model? Maybe a pretrained model can save my hard-working graphics card.

**Comment by lfang-salk** [comment]
I trained it last week. Leave your email here and I can send you one copy. Alternatively, there is a thread down under this Issue tab, go and find it, the author keeps generously sharing his pre-trained code to everybody. Either way works.

**Comment by tuxzz** [comment]
@lfang-salk Thanks for your sharing. I will find that issue.
My email: tuxzz<dorazzsoft@gmail.com>

**Comment by absaravanan** [comment]
@lfang-salk Hi, I am a computer vision enthusiast. I could not afford GPU's at the moment. Is it possible to share a pre-trained model with me ? Thanks

**Comment by Leeson111** [comment]
@lfang-salk could you send me a pretrained code that you have run, please? My email is 1450975631@qq.com.THANKS a lot.

**Comment by tangyudi** [comment]
@lfang-salk  Could you send me a pretrained model that you have run, please? My email is 474241623@qq.com.THANKS a lot.

**Comment by zsdonghao** [comment]
model in readme

**Comment by jcai20** [comment]
@lfang-salk Could you please send me the pre-trained model? Thanks for your help. My email is caijie0620@gmail.com

**Comment by jinsungroy** [comment]
Can you send it to me too? I really need trained model😂😂 My email address is jinsungroy@naver.com.
Thanks!
