### ISSUE TITLE
how to download g_srgan.npz,g_srgan_init.npz and d_srgan.npz files?

### ISSUE THREAD

**Issue by xuchenbupt** [tensorlayer/srgan#55]
HI,when i ran this project,i got a problem like ：
[!] Load checkpoint/g_srgan.npz failed!
[!] Load checkpoint/g_srgan_init.npz failed!
[!] Load checkpoint/d_srgan.npz failed!
Please download vgg19.npz from : https://github.com/machrisaa/tensorflow-vgg

but i can find vgg19.npz file in the website,how can i get these files?@zsdonghao
thank you!

**Comment by zsdonghao** [comment]
vgg https://github.com/machrisaa/tensorflow-vgg
g_srgan https://github.com/tensorlayer/srgan/issues/7
