### ISSUE TITLE
I am a newbie,I got some erros,could you help me solve it ,Please?

### ISSUE THREAD

**Issue by Leeson111** [tensorlayer/srgan#57]
Firstly, when I try to train the model,I got ResourceExhaustedError as following:
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[25088,4096]
	 [[Node: VGG19/fc6/W/Assign = Assign[T=DT_FLOAT, _class=["loc:@VGG19/fc6/W"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](VGG19/fc6/W, VGG19/fc6/W/Initializer/truncated_normal)]]
I have tried to changed the batch to 4,even 1,but it didn't work. Should I downscale the size of the images in HR training dataset? Secondly, when I used the trained model,it also get the wrong as following:
File "main.py", line 277, in evaluate
    valid_lr_img = (valid_lr_img / 127.5) - 1  # rescale to ［－1, 1]
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

**Comment by limchaos** [comment]
Smaller size images or better GPU

**Comment by luckyboysmith** [comment]
hello
i meet the same question when i test the model in evaluate as
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

have u solved it? hope to get your reply

**Comment by luckyboysmith** [comment]
@Leeson111
