### ISSUE TITLE
如何采用WGAN-GP来重新实现SRGAN?

### ISSUE THREAD

**Issue by gentleboy** [tensorlayer/srgan#59]
您好，我现在想在这份源代码的基础上用WGAN-GP来重新实现SRGAN，请问是否可行？如果可行的话，请问需要修改哪些地方？

目前我的想法是：
1、将生成器和判别器的损失函数改为WGAN-GP中的形式，采用WGAN-GP论文中的超参数，lambda = 10 , Adam(beta1=0.5, beta2=0.9)。
2、将判别器网络中的BatchNormLayer换成LayerNormLayer，去掉判别器最后的sigmoid激活函数。

我尝试做了以上修改，并且g_gan_loss、 mse_loss和vgg_loss的权重没有改动。我训练了几百个epochs，发现效果并不好，判别器的损失变成了负值。我感觉我的做法可能是错误的，或者是某些超参数没有设置好。非常希望能得到您的指导，谢谢！

**Comment by limchaos** [comment]
。。。。你先把文章看懂了再做吧，这都啥～

**Comment by huyangdi** [comment]
I have encountered the same problem. Have you solved it?
