### ISSUE TITLE
trained SRGAN model : https://github.com/tensorlayer/srgan/releases/tag/1.2.0

### ISSUE THREAD

**Issue by Andreababy** [tensorlayer/srgan#7]
Can you provide me your trained model? It takes me too much time to train the DIV2K dataset. @zsdonghao

**Comment by shawnyuen** [comment]
I need the trained model, too. Thank you , if you can provide me.
@zsdonghao

**Comment by zsdonghao** [comment]
what is your email address?

**Comment by Andreababy** [comment]
2018171324@qq.com   thank you

**Comment by zsdonghao** [comment]
i am testing a new implmentation of subpixel conv 2d, may send you after testing it.

**Comment by Andreababy** [comment]
Ok.

**Comment by Lakshya-Kejriwal** [comment]
Hi @zsdonghao i would also like to request that if you could provide me a copy of the trained model as well? Thanks

**Comment by zsdonghao** [comment]
@Lakshya-Kejriwal sure, give me your email.

**Comment by Lakshya-Kejriwal** [comment]
lkejri24@yahoo.com

**Comment by zsdonghao** [comment]
@Andreababy @Lakshya-Kejriwal i already send the model to you via wetransfer, please note that, this work is only for academic and non-commercial use only. For commercial use, please contact dhsig552@163.com.

**Comment by ABDOELSHEMY** [comment]
Hi @zsdonghao can you please send me a copy of the trained model ?thanks for your great and hard work.

**Comment by dxxz** [comment]
If you could send me a model, that would be greatly appreciate! my email address is yangchenj@gmail.com
Thanks!

**Comment by shawnyuen** [comment]
A single Titan X for training takes about 4 days...

**Comment by scalerhyme** [comment]
Hi. Could you please send me a copy of the trained model? My email address is mail@scalerhyme.com.
Another problem is that I cannot get the VGG19 model through the link you gave in the README file.
Thanks very much!

**Comment by jierice** [comment]
Could you please also send me the model? My email is jasongeophysics@gmail.com. I am running on CPU. It takes me three days to reach 20/2000. Thanks a lot.

**Comment by RichardIERG** [comment]
Could you please send me your trained model? My email address is hc85514301@gmail,com. Thanks a lot!

**Comment by flyywh** [comment]
Could you please send me your trained model? My email address is ywhlist150578209@gmail.com.  Thank you for sharing the work!

**Comment by zsdonghao** [comment]
@flyywh @jierice @RichardIERG please check your email, i send you via wetransfer.

**Comment by zsdonghao** [comment]
@shawnyuen for people, the result is not very good. I think the reason is that the training set do not have any people ~

**Comment by yanchenj** [comment]
Hey @zsdonghao , Could you please send me your trained model? I found training on my PC is super time consuming. My email is yangchenj@gmail.com. Thanks so much for sharing your work! I really appreciate!

**Comment by luochuwei** [comment]
Could you please send me your trained model? My email address is luochuwei@gmail.com. Thank you very much for sharing the work!

**Comment by listeng** [comment]
Great work! Could you please send me your trained model? Email: aosp@163.com. Thanks.

**Comment by jzrita** [comment]
May I add one more? Could you please send me your trained model? Email: jinzhi_126@163.com. Thanks.

**Comment by zsdonghao** [comment]
@jzrita @listeng @luochuwei @yanchenj  I already send the model to you via wetransfer, please note that, this work is only for academic and non-commercial use only. For commercial use, please contact dhsig552@163.com.

**Comment by jzrita** [comment]
@zsdonghao Hi, Donghao. The file has been well received and thank you very much.

**Comment by JustinhoCHN** [comment]
@zsdonghao hello, can you send me a copy of your trained model? Email: justinhochn@gmail.com ,thanks a lot!

**Comment by ZJiaQi** [comment]
May I add one more? Could you please send me your trained model? Email: zhang_jiaqi01@163.com. Thank you.

**Comment by ParanoidPY** [comment]
@zsdonghao 你好，我运行您的代码，出现了out of memory的错误，我的GPU为1080，8g显存。我想问一下这个是我配置原因么？您在什么配置下运行程序的？

**Comment by hufengshuo07** [comment]
@ParanoidPY I succeeded in training on one 1080ti with 11g graphics memory. Maybe you can try a smaller batch size.

**Comment by JustinhoCHN** [comment]
@ParanoidPY 我用的是1080ti，显存占用了8.5G左右，所以你把batch_size改成8吧，默认是16的。

**Comment by ParanoidPY** [comment]
@hufengshuo07 @JustinhoCHN  THANK YOU very much! i succeeded running the code with batch size 4! Is there any other ways to train the model with the batch size 16 in my hardware settings?

**Comment by Andreababy** [comment]
测试图片占的内存太大了，降低图片大小

**Comment by ghgh3269** [comment]
Could you please send me your trained model? email: ghgh3269@gmail.com  Thank you.

**Comment by JiahaoYao** [comment]
Could you please send me your trained model? email: zxc604036406@foxmail.com Thank you.

**Comment by zsdonghao** [comment]
Hi all, @JiahaoYao @ghgh3269 @ZJiaQi @JustinhoCHN sorry for the late reply, please check your email, I send it via wetransfer.

**Comment by JiahaoYao** [comment]
@zsdonghao Hi, Donghao. The file has been well received and thank you very much.

**Comment by JiahaoYao** [comment]
However, I have a silly question: when I set the BatchSize to be 16, it stuck into OOM problem; when I set the BatchSize to be 8, I have the following problem:
Traceback (most recent call last):
  File "main.py", line 316, in <module>
    train()
  File "main.py", line 144, in train
    tl.vis.save_images(sample_imgs_96, [ni, ni], save_dir_ginit+'/_train_sample_96.png')
  File "/home/deeplearning/SRGAN/SRGAN/tensorlayer/visualize.py", line 53, in save_images
    assert len(images) <= size[0] * size[1], "number of images should be equal or less than size[0] * size[1] {}".format(len(images))
AssertionError: number of images should be equal or less than size[0] * size[1] 8

I really want to run the code, what can I do?

**Comment by ZJiaQi** [comment]
Hi, Jiahao, where should I to find the file? I haven't found out model in my emails. Thanks.


发自网易邮箱大师
On 08/26/2017 22:36, Jiahao Yao wrote:

@zsdonghao Hi, Donghao. The file has been well received and thank you very much.

**Comment by zsdonghao** [comment]
@JiahaoYao check how to use `tl.vis.save_images` man

**Comment by ZJiaQi** [comment]
@zsdonghao I recevied the model, and I use the model you send to reconstruct the test images, but I got picture like this. What's wrong with me? Thank you.
![1_valid_sr](https://user-images.githubusercontent.com/23689986/29746465-ef10beba-8b0d-11e7-84b5-a347dd1988fd.png)

**Comment by zsdonghao** [comment]
@ZJiaQi Make sure the image format the same with the test code, I guess your image scale didn't rescale to -1 to 1.

**Comment by JustinhoCHN** [comment]
may I ask why we need to rescale the images to [-1, 1] ? Is this something like zero-centred data or something?

**Comment by JiahaoYao** [comment]
Thank you! We can change the BatchSize into 9.

**Comment by zsdonghao** [comment]
@JustinhoCHN it is for zero-centreing, just like other CNN training.

**Comment by DLjiaerlin** [comment]
@zsdonghao Could you please send me your trained model? I want to study it. Emai:jk747586650@163.com

**Comment by limwenyao** [comment]
@zsdonghao Hello, I would appreciate a copy of your trained model as well, thanks! Email: limwenyao@hotmail.com

**Comment by BloodLuna** [comment]
@zsdonghao Could you please send me your trained model? 
Emai:53756e4c69@gmail.com

**Comment by JiahaoYao** [comment]
I have a question, why there is always a memory error.
I have used 4 GPUs, K80. Did it mean that I would have to use even more GPUs.

[*] save images
[*] checkpoint/g_srgan.npz saved
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    train()
  File "main.py", line 246, in train
    tl.files.save_npz(net_d.all_params, name=checkpoint_dir+'/d_{}.npz'.format(tl.global_flag['mode']), sess=sess)
  File "/home/jhyao/deeplearning/SRGAN/SRGAN/tensorlayer/files.py", line 552, in save_npz
    np.savez(name, params=save_list_var)
  File "/home/jhyao/anaconda3/envs/deeplearning/lib/python3.6/site-packages/numpy/lib/npyio.py", line 593, in savez
    _savez(file, args, kwds, False)
  File "/home/jhyao/anaconda3/envs/deeplearning/lib/python3.6/site-packages/numpy/lib/npyio.py", line 703, in _savez
    pickle_kwargs=pickle_kwargs)
  File "/home/jhyao/anaconda3/envs/deeplearning/lib/python3.6/site-packages/numpy/lib/format.py", line 576, in write_array
    pickle.dump(array, fp, protocol=2, **pickle_kwargs)
MemoryError

**Comment by john820911** [comment]
@zsdonghao Can I also have your trained model? It would be much appreciated to have one :)
My email: [r05943135@ntu.edu.tw](url)

**Comment by naseeresmael** [comment]
@zsdonghao Could you please send me your trained model? My email address is omar44khatab@gmail.com. Thank you for sharing the work!

**Comment by zsdonghao** [comment]
Check your email for the model. 
Note that this work can't be used in commerical project.

**Comment by naseeresmael** [comment]
great I recevied the model, thank you @zsdonghao .

**Comment by yan7109** [comment]
@zsdonghao please share your trained model to derek.zh.yan@stanford.edu, thanks

**Comment by BloodLuna** [comment]
i got you mail,but the Transfer has deleted
Could you please send me your trained model again?
My Email : 53756e4c69@gmail.com
thank you

**Comment by Aixile** [comment]
@zsdonghao  Could you please send me your trained model? jinyh13@fudan.edu.cn, Thanks

**Comment by kankur** [comment]
@zsdonghao  Can you please send me the trained model on kadam.ankur04@gmail.com.

**Comment by wqi** [comment]
@zsdonghao Could I please get access to the trained model as well? My email is wiqi@alumni.ubc.ca. Many thanks!

**Comment by zsdonghao** [comment]
wiqi@alumni.ubc.ca kadam.ankur04@gmail.com jinyh13@fudan.edu.cn 53756e4c69@gmail.com derek.zh.yan@stanford.edu

Please check your email.

**Comment by moono** [comment]
Hello, @zsdonghao. May I ask for trained model too please? My email is toilety@gmail.com thanks in advance.

**Comment by tangyoubao** [comment]
Hi, @zsdonghao .Would you send the pre-trained model to me? Thanks. My email is tybxiaobao@gmail.com.

**Comment by Thanhhoang283** [comment]
Hi, @zsdonghao. Could you please send me your trained model? My email address is hoangducthanh283@gmail.com. Thanks in advance.

**Comment by iluhandric** [comment]
Hi, @zsdonghao! Thanks for the amazing work! Could you please send me your checkpoints? My email is solovev1910@gmail.com. Thanks!

**Comment by michalkoziarski** [comment]
@zsdonghao I'd be grateful for the model, michal.koziarski@gmail.com.

**Comment by zsdonghao** [comment]
check your emails.

**Comment by Flying-Sailor** [comment]
@zsdonghao Hi, thanks for sharing your awesome code :) , Could you please send me your pre-trained model. 
My email : volantmarin@gmail.com
Thanks.

**Comment by bautc** [comment]
That's amazing !
may I try out your pre-trained model ?
Thanks a lot !
email : bautc@yahoo.com

**Comment by akimin** [comment]
Could you please send me your trained model? My email address is akimin_lee@hotmail.com. Thanks a lot!

**Comment by kankur** [comment]
@zsdonghao  Thanks for your response. I got your model weights for 2X.
Do you have weights for 4X also? Please send on kadam.ankur04@gmail.com

**Comment by zsdonghao** [comment]
check your email.

**Comment by shipengtao** [comment]
@zsdonghao Hi, thanks for the awesome work!  Could you please send me your trained model? I hope it is  weights for 4X, My email address is ml2spt@gmail.com .  Thanks!

**Comment by laoyangui** [comment]
Hi, @zsdonghao.  Could you please send me your pre-trained model? My email address is fzu_su@126.com. Thanks!

**Comment by zhangwlgq** [comment]
Send me the pre-trained model please! 
My email address is zhangwlgq@gmail.com.
Thanks!

**Comment by Yolkis** [comment]
May i ask you for your pre-trained model?
Training the DIV2K dataset on my laptop CPU is takes too much time.
Share please.
yolkis@inbox.ru

**Comment by zmh0510** [comment]
Hi, @zsdonghao. I am a PHD student. I want to test some images in your model just for academic purpose. If you could send me a model, that would be greatly appreciate! My email address is 1260796864@qq.com.
Thanks!

**Comment by zsdonghao** [comment]
@zmh0510 @Yolkis @zhangwlgq @laoyangui @shipengtao Please check your email.

**Comment by benzhangwang** [comment]
@zsdonghao. Recently, I am learning about the GANs as my PHD topic, so I ask you to send me your trained model. My email is benzhang_wang@163.com. 
Thanks!

**Comment by comicchang** [comment]
Please send me the pretrained model, thank you
comicchang@gmail.com

**Comment by zhuguoguo123** [comment]
Could you please send me the pre-trained model?Thank you  very much . myaddress is 695839913@qq.com

**Comment by kankur** [comment]
I am unable to download 2X and 4X model weights due to file deleted by Wetransfer. Can you please send them again.

**Comment by Imanpour** [comment]
Do you have the trained networks at earlier epochs too? For examole at iteration 40 or 50 and so on. Because for my algorithm I can not wait until epoch 2000. I want to have earlier compare of the results for example at epoch 50.

**Comment by jiaozixian** [comment]
@zsdonghao Could you send me your trained model? Thank you very much. 345239728@qq.com

**Comment by Ianmcmill** [comment]
Hello, I would need some clarification as this is all new to me.
The instruction says that I need the VGG model and in ii. I need to have a dataset to train.
I guess the VGG model and a trained model is not the same? 
What is the difference?

And could you send me your pretrained model please? thegalaxynews@gmail.com

**Comment by hariag** [comment]
@zsdonghao could you please share your pre-trained model with me, thank you!
guochangzhu@qq.com

**Comment by stepByStepToSky** [comment]
Hi,

I just tried to train the SRGAN network. But it seems to take much time. Would you mind sending me the trained network for your code in link below:

https://github.com/zsdonghao/SRGAN

Thanks for your time and your kindness.

My email is 976434395@qq.com

**Comment by stepByStepToSky** [comment]
@zsdonghao 
Hi,
I just tried to train the SRGAN network. But it seems to take much time. Would you mind sending me the trained network for your code in link below:

https://github.com/zsdonghao/SRGAN

Thanks for your time and your kindness.

My email is 976434395@qq.com

**Comment by Imanpour** [comment]
Does your code have the ability to run on multiple GPU?

**Comment by tuxzz** [comment]
have anyone tested this model on anime images?

**Comment by Imanpour** [comment]
Still waiting...

**Comment by lnrd25** [comment]
Hi @zsdonghao, could you please send me your trained model? My email address is lanerd.rossi@gmail.com 
Thank you!

**Comment by liyuanye** [comment]
@zsdonghao 
liyuanye_bupt@163.com
thank you

**Comment by zsdonghao** [comment]
@liyuanye @lnrd25 @stepByStepToSky @hariag @Ianmcmill @jiaozixian @zhuguoguo123 @comicchang @Imanpour  @benzhangwang @kankur Hi all, please check your email.

**Comment by laur0312** [comment]
Hi, @zsdonghao, could you please provide me your trained model? My email address is laurance0312@126.com
Thank you

**Comment by kollisarath** [comment]
Hi, @zsdonghao , Can you please send the trained model to kollisarath@gmail.com

**Comment by naaktslaktauge** [comment]
Hi, @zsdonghao . Could u send me the trained model to naaktslak.taugetauge@gmail.com ??

**Comment by zhuguoguo123** [comment]
@zsdonghao  I have recevied the pre-trained model,  Thank you for your sharing .

**Comment by zhuguoguo123** [comment]
@zsdonghao Thank you for your sharing.Would you mind send me the pre_trained code  or where can i get it.

**Comment by RuijieHou** [comment]
hi, @zsdonghao Could you please send me your trained model to ruijiehou@gmail.com? Thanks a lot!

**Comment by jinyixin621** [comment]
Can someone send me a trained model???  @zsdonghao  jyx0621@gmail.com

**Comment by zsdonghao** [comment]
@jinyixin621 @RuijieHou @zhuguoguo123 @naaktslaktauge @kollisarath @laur0312 hi all, check your email.

**Comment by naseeresmael** [comment]
hi @zsdonghao could you please send me your model weights for 2X my mail abdo333pasha@gmail.com

**Comment by xws117** [comment]
@zsdonghao  大神可以发我一份训练模型吗？ 我的邮箱是1179066213@qq.com

**Comment by q512624756** [comment]
@zsdonghao Can u please send the trained model to wxa789789@163.com ?thank you very much!!!

**Comment by feiyun1265** [comment]
Hi, @zsdonghao. Can you please send me your pre-trained model? My email address is chshfmail@163.com. I just use the model for study, Thanks!

**Comment by JimKlingshirn** [comment]
Hi, @zsdonghao, could you please provide me your trained model? My email address is JimKlingshirn@gmail.com
Many Thanks!

**Comment by scalerhyme** [comment]
Hi, @zsdonghao. Could you please send me your trained model? My email address is yydjtc1990@gmail.com. Thanks!

**Comment by dojure** [comment]
Thanks for this fantastic work @zsdonghao, I would very much appreciate your trained model as well, if you don't mind. etienned@ethz.ch

**Comment by T-tssxuan** [comment]
Hi, @zsdonghao, thanks for your great work, could you please share your model as competitor in my work? thanks a lot, louxuan@bupt.edu.cn

**Comment by zsdonghao** [comment]
@T-tssxuan @dojure @scalerhyme @JimKlingshirn @feiyun1265 @q512624756 @xws117 @naaktslaktauge please check your email.

**Comment by feiyun1265** [comment]
Dear @zsdonghao, I have checked my email, but i did not receive the trained model, can you send me again, my email:chshfmail@163.com, Thank you for your share!

**Comment by scalerhyme** [comment]
Hi, @zsdonghao. I'm sorry that I haven't received the model you sent to me in my email. Could you please send again(yydjtc1990@gmail.com)? Thanks so much!

**Comment by zsdonghao** [comment]
@scalerhyme please check the wetransfer email

**Comment by scalerhyme** [comment]
Thank you! I got the email this time! :)

Hao <notifications@github.com>于2017年11月26日周日 下午8:47写道：

**Comment by lorhm** [comment]
Hey @zsdonghao , really appreciate you sharing your work!
It would be great if you could mail the model to me at:  rahul95ram@gmail.com
Cheers!

**Comment by padwha** [comment]
Impressed by your work and thank you for sharing.
It would be greatly appreciated if you can send me the trained model.
My email address is "dwookha@gmail.com"
Thank you!

**Comment by RachitB11** [comment]
Hi, it would be great if you could send me the trained model as well on "rachitbh@seas.upenn.edu"
I'm facing memory issues using the default batch size of 16 on a 4gb 1050 Ti.

**Comment by kevinjoseph1995** [comment]
Hey, @zsdonghao it would be awesome if you could share the trained model, as training on my machine is just taking too long. Email: kevjoseph@umass.edu

**Comment by zsdonghao** [comment]
@kevinjoseph1995 @RachitB11 @padwha @scalerhyme hi, please check the wetransfer email.

**Comment by hankobe** [comment]
@zsdonghao Can I also have your train model? My email is "hanjoey882@163.com". Thank you very much.

**Comment by carlblocking** [comment]
你好。如果我想尝试2倍放大情况下的超分该怎么做呢？本科生刚开始接触，还不大会改代码，还望指导一下

**Comment by zsdonghao** [comment]
@carlblocking 去掉一层 supbixconv

**Comment by yhy1993824** [comment]
@zsdonghao May I add one? It will be great if you could send the training model to me. My e-mail is "yhy1993824@gmail.com". Thank you very much.

**Comment by xxccry** [comment]
Hi @zsdonghao , I  would also like to request that if you could provide me a copy of the trained model as well? Thanks

**Comment by dgrinb01** [comment]
Hi @zsdonghao , can you please send me the trained model? My email is dgwbox-in@yahoo.com , Thank you.

**Comment by marbleappdev** [comment]
@zsdonghao could you please email me the trained model? My email is us.klee@gmail.com.  Thank you!

**Comment by HazekiahWon** [comment]
@zsdonghao Thanks for your brilliant work and sharing your code, it's really shedding light on me. 
While my repoducing your work, however, the resulting HR image appears somehow darker (check it below). So I would greatly appreciate it if you could email me your trained model so that I can make further survey and comparisons. My email is [1470468661@qq.com](mailto:1470468661@qq.com)
![valid_bicubic](https://user-images.githubusercontent.com/20485949/33725912-8f06421e-dbae-11e7-89eb-9b9b5242bae1.png)
![valid_gen](https://user-images.githubusercontent.com/20485949/33725919-93aeeb86-dbae-11e7-81ec-12a1d61abeb4.png)
this is evaluated after an 1000/2000 epoch of adversarial training using your architecture, trained on 1080ti 12g x3, not having modified hyperparameters except for the loading manner of the training data.

**Comment by zsdonghao** [comment]
hi @yhy1993824 @xxccry @dgrinb01 @marbleappdev @HazekiahWon , please check the wetransfer email

**Comment by SmezMorePrakezz** [comment]
@zsdonghao Can you provide me the trained model. Please :-) My e-mail is golfpokaeo@gmail.com

**Comment by ourana35** [comment]
@zsdonghao  Could you please send me your improved trained model? Thanks. My email address: yyena35@163.com

**Comment by usmanxia** [comment]
@zsdonghao  Can you please email your pre-trained model. My email is usman.phd@students.mcs.edu.pk.

Thank you

**Comment by ishmael1985** [comment]
@zsdonghao , I would like to test out your pre-trained model. Giving out my email as follows.
ishmael1985@gmail.com

Thanks!

**Comment by JohnnieXDU** [comment]
@zsdonghao Could you please send me your trained model? 767175262@qq.com, Thanks

**Comment by jcarra** [comment]
@zsdonghao I tried training the model myself but my GPU is not up to the task. Can I have the model too? This is my email: kuxumice@nada.email
Thank you, and great work!

**Comment by zsdonghao** [comment]
check email.

**Comment by echowjm** [comment]
If you could send me a model, that would be greatly appreciate! my email address is 549880890@qq.com Thanks!

**Comment by jcarra** [comment]
Thank you zsdonghao! I will still try to experiment and to modify the code to allow "multi-session" training too. (the word "checkpoint" made me think this was already working that way)

**Comment by limchaos** [comment]
哇哇哇哇，求一发训练好的模型，好人一生平安嘿嘿，dingyf0101@163.com

**Comment by NathanielNguyen11** [comment]
Dear Mr Dong. 
Thank for your public implementation very much
May you send me the trained model?  my email is : ngocquang870@gmail.com

**Comment by lfang-salk** [comment]
Hi Dong,

I am currently training the posted model in my computer, while at the same time, would it be possible to test my images in your pre-trained one? My email address is lfang@salk.edu. Thank you in advance and happy holiday!

Lynn

**Comment by zsdonghao** [comment]
hi, please check the email~

**Comment by lfang-salk** [comment]
Thank you Hao!!

Lynn

Get Outlook for iOS<https://aka.ms/o0ukef>



On Thu, Dec 21, 2017 at 7:46 PM -0800, "Hao" <notifications@github.com<mailto:notifications@github.com>> wrote:


hi, please check the email~

-

**Comment by mrwen00** [comment]
Hello there, Can you send me the trained model? 
My email: mrwen00@gmail.com
Thank you very much.

**Comment by freedom825** [comment]
@zsdonghao , Could you please send me the trained model to gf_zhang@163.com? merry christmas!

**Comment by tpys** [comment]
@zsdonghao I already start to train  with your code, But it seems to take a long time, Could you please send your trained model,  Thanks a lot. 
My email: lchen80@163.com

**Comment by zsdonghao** [comment]
**IMPORTANT**

**Hi all, this project is now become an example in this [book](http://www.broadview.com.cn/book/5059).**

**For the model, please download [32622.zip](http://www.broadview.com.cn/file/resource/046025086042215124052015222146047067012031094199) and find the `g_srgan.npz`.**

**Best wishes**

**Comment by tpys** [comment]
@zsdonghao Thanks for great contribution and excellent book.

**Comment by mrwen00** [comment]
@zsdonghao Could you give me the link to download model "g_srgan.npz" I don't know where to download "下载资源 32622.zip" Thank you.

**Comment by ratsuki** [comment]
can you give me the trained model,thank you!
my email : 651406101@qq.com

**Comment by zsdonghao** [comment]
@ratsuki check my above answer

**Comment by ratsuki** [comment]
I download 32622.zip and only find the g_srgan.npz,but where is d_srgan.npz?

**Comment by zhuyanshuo** [comment]
can you give me the trained model,thank you!
my email: 1240368588@qq.com

**Comment by weikaichenusc** [comment]
@zsdonghao could u send me the pretrained model? thank you! my email: chenwk891@gmail.com

**Comment by automan000** [comment]
@zsdonghao Hi, could you send me the pretrained model? Thank you so much. My email: zhuangzj15@mails.tsinghua.edu.cn

**Comment by Jillian2017** [comment]
Your pretrained model is needed,  could you please send me? My email:zhoujing9204@163.com. Thanks a lot.

**Comment by virata** [comment]
@zsdonghao Hi, 
Can you give me the trained model?
Thank you for your work.
my email address : virata@naver.com

**Comment by zsdonghao** [comment]
**IMPORTANT ==================================**



**Hi all,**

**This project is now become an example of this [book](http://www.broadview.com.cn/book/5059).**

**For the model, please download [下载资源 32622.zip](http://www.broadview.com.cn/book/5059) and find the `g_srgan.npz`.**

**Best wishes**

**Hao**



**IMPORTANT ==================================**



**Hi all,**

**This project is now become an example of this [book](http://www.broadview.com.cn/book/5059).**

**For the model, please download [下载资源 32622.zip](http://www.broadview.com.cn/book/5059) and find the `g_srgan.npz`.**

**Best wishes**

**Hao**



**IMPORTANT ==================================**



**Hi all,**

**This project is now become an example of this [book](http://www.broadview.com.cn/book/5059).**

**For the model, please download [下载资源 32622.zip](http://www.broadview.com.cn/book/5059) and find the `g_srgan.npz`.**

**Best wishes**

**Hao**



**IMPORTANT ==================================**



**Hi all,**

**This project is now become an example of this [book](http://www.broadview.com.cn/book/5059).**

**For the model, please download [下载资源 32622.zip](http://www.broadview.com.cn/book/5059) and find the `g_srgan.npz`.**

**Best wishes**

**Hao**



**IMPORTANT ==================================**



**Hi all,**

**This project is now become an example of this [book](http://www.broadview.com.cn/book/5059).**

**For the model, please download [下载资源 32622.zip](http://www.broadview.com.cn/book/5059) and find the `g_srgan.npz`.**

**Best wishes**

**Hao**



**IMPORTANT ==================================**



**Hi all,**

**This project is now become an example of this [book](http://www.broadview.com.cn/book/5059).**

**For the model, please download [下载资源 32622.zip](http://www.broadview.com.cn/book/5059) and find the `g_srgan.npz`.**

**Best wishes**

**Hao**



**IMPORTANT ==================================**



**Hi all,**

**This project is now become an example of this [book](http://www.broadview.com.cn/book/5059).**

**For the model, please download [下载资源 32622.zip](http://www.broadview.com.cn/book/5059) and find the `g_srgan.npz`.**

**Best wishes**

**Hao**



**IMPORTANT ==================================**



**Hi all,**

**This project is now become an example of this [book](http://www.broadview.com.cn/book/5059).**

**For the model, please download [下载资源 32622.zip](http://www.broadview.com.cn/book/5059) and find the `g_srgan.npz`.**

**Best wishes**

**Hao**

**Comment by Leeson111** [comment]
May I add one more? Could you please send me your trained model? Email: 1450975631@qq.com. Thank you.

**Comment by zsdonghao** [comment]
@Leeson111 Could you please download it yourself?? 你能不能自己点进去下载呢？谢谢！

**Comment by Leeson111** [comment]
哥哥，我下载速度只有几K

**Comment by zsdonghao** [comment]
@Leeson111 as your internet is poor, I can't help, sorry about that..

**Comment by Leeson111** [comment]
谢谢好心的哥哥

**Comment by Leeson111** [comment]
I am very very very sad ,blue ,sarrow.

**Comment by foreverseer** [comment]
i run it and its said that my CPU is not support, how to work it out?
the other question how to use GPU to accelerate , if i use CPU i will take 1 month 
thanks a lot to author

**Comment by varunrao1991** [comment]
Could you please send me the trained model? [varunrao.rao@gmail.com](url)

**Comment by AldoMarzullo** [comment]
Hi, could someone please send me the trained model? emme.aldo24@yahoo.it
Thanks for your help!

**Comment by InderpreetSinghChhabra01** [comment]
Can you please send me the trained model, since I can't read Chinese I am unable to type verification code on the website you mentioned. chhabra.2@iitj.ac.in

**Comment by tangyudi** [comment]
@zsdonghao Hi,thank you for sharing.My email is 474241623@qq.com.

**Comment by jimlynnjulian** [comment]
Hello,
   SRGAN crashes when d_srgan.npz is not found. I've looked at all the locations pointed to by the links but only g_srgan is avalable. Can d_srgan be built? My email is 
 jimlynnjulian2@yahoo.com
I'm using release 1.2.1 with the g_srgan.npz from release 1.2.0.
Thank you.

**Comment by zsdonghao** [comment]
please dont ask me for model, it is in readme!

**Comment by linhdvu14** [comment]
What data was the current pretrained model trained on?

**Comment by RigoYao** [comment]
Could you please send me your trained model? My email address is rigoyao@163.com. Thank you for sharing the work! @zsdonghao

**Comment by SalmaAhmed95** [comment]
May I ask how to run the pretrained model ?
