### ISSUE TITLE
Resource exhausted: OOM when allocating tensor

### ISSUE THREAD

**Issue by arisliang** [tensorlayer/srgan#73]
It seems GPU RAM exhausted when tensorflow trying to load all training data. How much RAM does it need to load all training data. I'm on 6GB card.

**Comment by zsdonghao** [comment]
try reduce the batch size

**Comment by arisliang** [comment]
batch size 16 that batch size?

**Comment by zsdonghao** [comment]
yeah, try batch size of 8?

**Comment by arisliang** [comment]
i think ni doesn't like to be sqrt of 8.

`
Traceback (most recent call last):
  File "/home/ly/src/tl-play/ch13/ch13_srgan.py", line 104, in <module>
    tl.vis.save_images(sample_imgs_96, [ni, ni], save_dir_ginit+'/_train_sample_96.png')
  File "/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/tensorlayer/visualize.py", line 134, in save_images
    assert len(images) <= size[0] * size[1], "number of images should be equal or less than size[0] * size[1] {}".format(len(images))
AssertionError: number of images should be equal or less than size[0] * size[1] 8
`

**Comment by arisliang** [comment]
4 works, but i think it's too much of a toy number.

**Comment by zsdonghao** [comment]
you can modify the `tl.vis.save_images` to `tl.vis.save_images(images, [2, 4])` for batch size of 8.

**Comment by arisliang** [comment]
yes, batch size of 8 works with the above change.

**Comment by arisliang** [comment]
turned out, batch size 8 is ok for initial training, but still too big for subsequent adversarial training. Reduced to 6 to see (need to change batch size in placeholder declaration to None, because of 800 images for batch size 6, the last batch would be 2 images)
