### ISSUE TITLE
Possibility to train d and g on different GPU?

### ISSUE THREAD

**Issue by arisliang** [tensorlayer/srgan#74]
Just curious, can we split the discriminator and generator on different device to speed up the training?

**Comment by chensongkui** [comment]
of course no,because the discriminator need the output of the generator.

**Comment by zsdonghao** [comment]
you can try `with tf.device("gpu0/1")" for G and D to see whether it works or not.

**Comment by arisliang** [comment]
@chensongkui Even one needs the output of the other, it's still possible to split the work and speed up. Say D depends on G's output. G starts to work on batch 1 and D idle, after G finish, D starts to work on batch 1, in the meantime, G can start to work on batch 2. So G works 1 batch lead of D, because of the output dependency. But possible for the two to work in parallel.

@zsdonghao I don't have the luxury of two cards now unfortunately. Maybe someone who has can try it out.
