### ISSUE TITLE
NameError: name 'time' is not defined

### ISSUE THREAD

**Issue by shede1988** [tensorlayer/srgan#76]
NameError: name 'time' is not defined

**Comment by shede1988** [comment]
start_time = time.time()
这一行报错，要怎么改呢？

**Comment by shede1988** [comment]
import time 就好了

**Comment by dragon-web** [comment]
![image](https://user-images.githubusercontent.com/55302135/135442939-70183d1d-35fe-4fb6-bf50-841403045158.png)
出现了这个错误
