### ISSUE TITLE
Need d_srgan.npz

### ISSUE THREAD

**Issue by scutdyk** [tensorlayer/srgan#88]
I can not find d_srgan.npz, who have it?
Please send a copy to me, thanks.
My email is dai957740699@yahoo.com.

**Comment by Heermosi** [comment]
Me too!
May you put a copy of d_srgan.npz on the website?
If you can't, can you just tell me how long does it take to train a fresh new model with a single 1080Ti?

**Comment by zsdonghao** [comment]
that model is 200mb, too large to share.

actually, you don't need that, if you really want it, you can load the `g_srgan.npz` and train it for several epochs.

**Comment by zsdonghao** [comment]
@scutdyk if you don't have any other question related to this issue, please close it. thanks
