### ISSUE TITLE
Why do we use SRGAN_d instead of SRGAN_d2 in the function of main.py 

### ISSUE THREAD

**Issue by Alxemade** [tensorlayer/srgan#93]
Hello,
     when I read your code, I have some questions about the code.  why you use SRGAN_d instead of [SRGAN_d2](https://github.com/tensorlayer/dcgan/blob/master/model.py) in the function of [main.py ](https://github.com/tensorlayer/dcgan/blob/master/main.py) 。 The code for this discriminator also appears in your other code  [DAGAN](https://github.com/nebulaV/DAGAN/blob/master/model.py), Why can I use it like this,what are the benefits? 
     I was hoping you could help me with this problem, I can't get it right.

**Comment by zsdonghao** [comment]
for smaller network size

**Comment by Alxemade** [comment]
@zsdonghao , Thank you for your reply!
