### ISSUE TITLE
A question about image save

### ISSUE THREAD

**Issue by hahazhky** [tensorlayer/srgan#94]
Hello
I noticed the hr images is in [-1, 1], so generated images are approximately in this range, why it can be save as image directly, is it scale to [0, 255]? why it is not clipped to [0, 1] then convert to [0, 255]
And your generated result are all in [-1, 1]? my results is almost in [0, 1.xx], does it have any bad effects on extracting vgg features from them?
Thanks a lot

**Comment by zsdonghao** [comment]
The save image API automatically deal with the scale for you, so it can be saved in any scale
